include: 
  - docker-compose.prod.yaml

services:
  dex:
    image: ghcr.io/dexidp/dex:v2.42.0
    command: dex serve /etc/dex/config.yml
    volumes:
      - ./dex/config.yml:/etc/dex/config.yml:ro
      - dex_data:/var/dex
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - c2
    labels:
      - traefik.enable=true
      - traefik.http.services.dex.loadbalancer.server.port=5556
      - traefik.http.routers.dex.rule=Host(`auth.localhost`) || Host(`auth.kiosk.mnta.in`)

  certgen:
    image: alpine:latest
    command: >
      sh -c "
      apk add --no-cache openssl &&
      mkdir -p /certs &&
      if [ ! -f /certs/privkey.pem ]; then
        echo 'Generating self-signed cert...';
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /certs/privkey.pem -out /certs/fullchain.pem -subj '/CN=localhost';
      fi
      "
    volumes:
      - ./nginx/certs:/certs


volumes:
  dex_data:

networks:
  c2:
