services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    command: "-js -m 8222"
    restart: unless-stopped
    networks:
      - c2

  clients:
    build: ./clients
    depends_on:
      - nats
    restart: unless-stopped
    volumes:
      - static_plugins:/static/plugins/
    networks:
      - c2
    labels:
      - traefik.http.services.clients.loadbalancer.server.port=8000
      - traefik.http.routers.clients.rule=HostRegexp(`[0-9a-f]\.clients\..*`) || HostRegexp(`clients\..*`)
      - traefik.enable=true


  website-bundler:
    build: ./website-bundler
    depends_on:
      - nats
    restart: unless-stopped
    networks:
      - c2

  plugins:
    build: ./plugins
    depends_on:
      - nats
    restart: unless-stopped
    volumes:
      - static_plugins:/static/
    networks:
      - c2

  ui:
    build: ./ui/
    depends_on:
      - nats
    restart: unless-stopped
    networks:
      - c2
    labels:
      - traefik.http.services.api.loadbalancer.server.port=8000
      - traefik.http.routers.api.rule=PathPrefix(`/`)
      - traefik.enable=true

  traefik:
    image: traefik:3.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/dynamic.yml:/dynamic.yml
    extra_hosts:
      idp: 172.16.1.142
    ports:
      - "80:80"
    networks:
      - c2
    restart: unless-stopped

volumes:
  static_plugins:

networks:
  c2: