http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Provider:
            Url: https://auth.localhost
            ClientId: traefik
            ClientSecret: traefik-local-secret
          LogLevel: DEBUG
          BypassAuthenticationRule: >
            PathPrefix(`/client`) ||
            Host(`auth.localhost`) || Host(`auth.kiosk.mnta.in`) ||
            HostRegexp(`clients\..*`)
          Scopes:
            - openid
            - profile
            - email
          SessionCookie:
            Secure: true
