http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Provider:
            Url: https://auth.localhost
            ClientId: traefik
            ClientSecret: traefik-local-secret
            InsecureSkipVerify: true
          LogLevel: DEBUG
          BypassAuthenticationRule: >
            PathPrefix(`/clients`) ||
            Host(`auth.localhost`) || Host(`auth.kiosk.mnta.in`)
          Scopes:
            - openid
            - profile
            - email
          SessionCookie:
            Secure: false
