api:
  dashboard: true
  insecure: true

accesslog:
  addInternals: true

entryPoints:
  web:
    address: :80
    forwardedHeaders:
      insecure: true   # all traffic comes from nginx on the same Docker network
    http:
      middlewares:
        - oidc-auth@file

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  file:
    filename: /dynamic.yml
    
experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: github.com/sevensolutions/traefik-oidc-auth
      version: v0.18.0